CREATE TABLE user_order (
                        id BIGSERIAL PRIMARY KEY,
                        order_uid VARCHAR(255),
                        track_number VARCHAR(255),
                        entry VARCHAR(255),
                        locale VARCHAR(255),
                        internal_signature VARCHAR(255),
                        customer_id VARCHAR(255),
                        delivery_service VARCHAR(255),
                        shardkey VARCHAR(255),
                        sm_id INT,
                        date_created TIMESTAMP,
                        oof_shard INT,
                        name VARCHAR(255),
                        phone VARCHAR(255),
                        zip VARCHAR(255),
                        city VARCHAR(255),
                        address VARCHAR(255),
                        region VARCHAR(255),
                        email VARCHAR(255),
                        transaction VARCHAR(255),
                        request_id VARCHAR(255),
                        currency VARCHAR(255),
                        provider VARCHAR(255),
                        amount FLOAT,
                        payment_dt BIGINT,
                        bank VARCHAR(255),
                        delivery_cost FLOAT,
                        goods_total FLOAT,
                        custom_fee INT
);

CREATE TABLE item (
                       id BIGSERIAL PRIMARY KEY,
                       user_order_id BIGSERIAL,
                       chrt_id INT,
                       track_number VARCHAR(255),
                       price FLOAT,
                       rid VARCHAR(255),
                       name VARCHAR(255),
                       sale FLOAT,
                       size FLOAT,
                       total_price FLOAT,
                       nm_id INT,
                       brand VARCHAR(255),
                       status INT,
                       FOREIGN KEY (user_order_id) REFERENCES user_order (id)
);