CREATE TABLE user_order (
                        id BIGSERIAL PRIMARY KEY,
                        order_uid VARCHAR(255) DEFAULT '',
                        track_number VARCHAR(255) UNIQUE DEFAULT '',
                        entry VARCHAR(255) DEFAULT '',
                        locale VARCHAR(255) DEFAULT '',
                        internal_signature VARCHAR(255) DEFAULT '',
                        customer_id VARCHAR(255) DEFAULT '',
                        delivery_service VARCHAR(255) DEFAULT '',
                        shardkey VARCHAR(255) DEFAULT '',
                        sm_id INT DEFAULT 0,
                        date_created TIMESTAMP DEFAULT 'epoch',
                        oof_shard INT DEFAULT 0,
                        name VARCHAR(255) DEFAULT '',
                        phone VARCHAR(255) DEFAULT '',
                        zip VARCHAR(255) DEFAULT '',
                        city VARCHAR(255) DEFAULT '',
                        address VARCHAR(255) DEFAULT '',
                        region VARCHAR(255) DEFAULT '',
                        email VARCHAR(255) DEFAULT '',
                        transaction VARCHAR(255) DEFAULT '',
                        request_id VARCHAR(255) DEFAULT '',
                        currency VARCHAR(255) DEFAULT '',
                        provider VARCHAR(255) DEFAULT '',
                        amount FLOAT DEFAULT 0.0,
                        payment_dt BIGINT DEFAULT 0,
                        bank VARCHAR(255) DEFAULT '',
                        delivery_cost FLOAT DEFAULT 0.0,
                        goods_total FLOAT DEFAULT 0.0,
                        custom_fee INT DEFAULT 0

);

CREATE TABLE item (
                       id BIGSERIAL PRIMARY KEY,
                       user_order_id BIGSERIAL,
                       chrt_id INT DEFAULT 0,
                       track_number VARCHAR(255) DEFAULT '',
                       price FLOAT DEFAULT 0.0,
                       rid VARCHAR(255) DEFAULT '',
                       name VARCHAR(255) DEFAULT '',
                       sale FLOAT DEFAULT 0.0,
                       size FLOAT DEFAULT 0.0,
                       total_price FLOAT DEFAULT 0.0,
                       nm_id INT DEFAULT 0,
                       brand VARCHAR(255) DEFAULT '',
                       status INT DEFAULT 0,
                       FOREIGN KEY (user_order_id) REFERENCES user_order (id)
);